In [4]:
import numpy as np
a=[1,2,3,4]
b=[2,3,4,5]

a=np.array(a)
b=np.array(b)

a*b

array([ 2,  6, 12, 20])

In [5]:
np.array([1,2,3,4,5])
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [6]:
np.zeros(10,dtype=int)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.random.normal(10,4,(3,4) )

array([[10.21581267, 13.4019507 ,  7.98321911, 12.11246778],
       [14.00760615, 12.89271392, 10.94886583, 10.4709861 ],
       [15.79960585,  2.64167857, 18.72249556,  9.20535796]])

In [8]:
a=np.random.randint(10,size=5)
a.ndim
a.shape
a.size
a.dtype

dtype('int64')

**numpy arraylari !!!!!!!!!!!!!!!!!!!!**

In [9]:
v=np.array([1,2,3,4,5])

v<3

array([ True,  True, False, False, False])

In [10]:
#fancy
list=[3,4]
v[list]

array([4, 5])

In [11]:
v[v<3]

array([1, 2])

In [12]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [13]:
np.min(v)

1

In [14]:
np.sum(v)
np.mean(v)
np.var(v)
np.std(v)
np.median(v)

3.0

In [15]:
#5*x0 + x1=12
#x0+2*x1=10
a=np.array([[5,1],[1,2]])
b=np.array([12,10])
x=np.linalg.solve(a,b)
x

array([1.55555556, 4.22222222])